/* Gate: the weight ceiling, and every declared face exists on disk.
 *
 * This file used to police the desktop app's private <style> block - a second
 * visual identity for the same product, and the half nobody was checking. The
 * desktop app is gone, so that half of the gate went with it rather than being
 * repaired: there is one interface now, and web/css/base.css is where its
 * vocabulary lives. The rule that base.css defines and every other sheet
 * consumes is enforced by tests/test_design_system.py, which needs neither
 * Chrome nor Node.
 *
 * What remains here needs Node, which is why it is still a .mjs: the ceiling
 * has to read the token *values*, the face declarations and the files on disk
 * together, and a ceiling checked in one of three places is a ceiling with two
 * holes in it.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(here, "..", "..", "web");

/* The FULL vendored palette, not the pruned sheet the page ships.
   web/heyoz-tokens.css is generated by tools/gen_tokens_subset.py and contains
   only the tokens this app reaches, so a weight token nothing consumes is - by
   design - absent from it. This gate resolves weight tokens that the CONSUMERS
   below reference, and it must be able to look up any weight the palette can
   express: reading the pruned copy made every lookup miss, which turned "no
   token renders above 600" into "no token was checked". */
const tokens = readFileSync(
  path.resolve(WEB, "..", "vendor", "heyoz-tokens.css"), "utf8");
const fontsCss = readFileSync(path.join(WEB, "fonts.css"), "utf8");

/* Every sheet the page actually loads, plus the page itself. The palette is
   allowed to *define* a bold it never uses; the rule is about what renders. */
const CONSUMERS = [
  "index.html",
  "css/base.css", "css/layout.css", "css/controls.css",
  "css/queue.css", "css/compare.css",
];
const consumed = CONSUMERS
  .map((rel) => { try { return readFileSync(path.join(WEB, rel), "utf8"); }
                  catch { return ""; } })
  .join("\n");

let bad = 0;

/* ----------------------------- weight ceiling ----------------------------- */

/* Nothing may render above semibold, in any instance. Three ways that could be
   broken, so all three are checked: a numeric font-weight over 600, a token
   whose value exceeds 600, and a self-hosted face whose variable range reaches
   past it. */
const CEILING = 600;

const tokenWeights = new Map(
  [...tokens.matchAll(/^\s*(--oz-(?:weight|default-weight)-[a-z]+)\s*:\s*(\d+)/gm)]
    .map((m) => [m[1], Number(m[2])]));

/* A literal over the ceiling, anywhere the page styles from. */
for (const m of consumed.matchAll(/font-weight\s*:\s*(\d{3})\b/g)) {
  if (Number(m[1]) > CEILING) {
    console.log(`  WEIGHT literal ${m[1]} > ${CEILING}`); bad++;
  }
}

/* Or a token reference whose value is over it. Defining a heavier weight in the
   palette is not the violation - reaching for it is. */
for (const m of consumed.matchAll(/var\((--oz-(?:weight|default-weight)-[a-z]+)\)/g)) {
  const v = tokenWeights.get(m[1]);
  if (v > CEILING) {
    console.log(`  WEIGHT ${m[1]} is ${v} > ${CEILING}`); bad++;
  }
}

for (const m of fontsCss.matchAll(/font-weight\s*:\s*(\d{3})(?:\s+(\d{3}))?/g)) {
  const top = Number(m[2] || m[1]);
  if (top > CEILING) {
    console.log(`  WEIGHT fonts.css: face range tops at ${top} > ${CEILING}`); bad++;
  }
}

const faces = [...fontsCss.matchAll(/url\('\/fonts\/([^']+)'\)/g)].map((m) => m[1]);
console.log(`weight ceiling ${CEILING}: checked ${tokenWeights.size} tokens, `
            + `${faces.length} self-hosted faces`);

/* A face that is not there is text silently falling back to a system font. */
for (const f of new Set(faces)) {
  try { readFileSync(path.join(WEB, "fonts", f)); }
  catch { console.log(`  MISSING FONT ${f}`); bad++; }
}

/* The gate is only worth having if it read something. A refactor that renames
   the token prefix or moves the @font-face rules would otherwise leave every
   loop above iterating over nothing and still print OK. */
if (!tokenWeights.size) {
  console.log("  read 0 weight tokens out of heyoz-tokens.css - the gate measured nothing");
  bad++;
}
if (!faces.length) {
  console.log("  read 0 self-hosted faces out of fonts.css - the gate measured nothing");
  bad++;
}

console.log(bad === 0
  ? `\nOK — no weight above ${CEILING}, every declared face present`
  : `\n${bad} problem(s)`);
process.exit(bad ? 1 : 0);
