"""Build the awkward-input corpus: the shapes real video actually arrives in.

The benchmark corpus in `make_video_fixtures.py` is about content - what
compresses well and what does not. This one is about *containers and
metadata*, which is where a video compressor silently produces wrong output
rather than merely a large file.

Every clip here is modelled on something a person genuinely hands a
compressor:

- `portrait`    a phone held upright. The picture is stored landscape with a
                rotation flag, and a tool that ignores the flag writes a
                sideways video. This is the single most common consumer video
                shape in existence.
- `upside`      the same trick at 180 degrees, which a phone records when it
                is held the other way up.
- `anamorphic`  non-square pixels, as DV and many camera modes produce. The
                stored frame is not the shape the picture should be, and a
                tool that ignores it writes a squashed video.
- `hdr`         10-bit BT.2020 with a PQ transfer, which is what an HDR10
                phone or camera records. Converting it naively to 8-bit SDR
                produces a washed-out picture where white comes out grey.
- `hlg`         the *other* high dynamic range format, and the one Apple
                actually records: same picture, same absolute brightness,
                entirely different transfer curve. Two clips that must come
                out of the compressor looking the same.
- `sdr10`       ordinary BT.709 colour that merely happens to be 10-bit. The
                control: nothing here may be tone mapped, because tone mapping
                a picture that was already correct crushes it.
- `phone`       both at once - held upright *and* high dynamic range, which is
                not an exotic combination but the literal default setting of
                the most common camera on earth. Straightening and converting
                have to compose, and they run in the same filter graph.
- `vfr`         variable frame rate, as screen recorders and phones produce.
                Timestamps are uneven, and a tool that assumes a constant rate
                drifts out of sync with the sound.
- `multitrack`  two audio tracks. Dropping one silently loses content.

**The colour maths here is written out again rather than imported from
`pocketsize.video`.** That is deliberate and it is the only reason these
fixtures prove anything: a corpus generated by the code under test can only
ever confirm that the code agrees with itself. These are the forward
directions - scene light to a code value - taken straight from ST 2084 and
BT.2100, and the engine has to invert them without ever having seen them.

Reproduce with:

    python tests/make_real_world_fixtures.py
"""

from __future__ import annotations

import math
import sys
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "real_world_fixtures"

WIDTH, HEIGHT, FPS, SECONDS = 480, 270, 24, 2

# The two brightnesses the HDR clips are built around, both from ITU-R
# BT.2408: 203 nits is what "white" means in high dynamic range, and 1000 is
# the peak a consumer master is graded to. A conversion that gets these two
# right has got the picture right.
HDR_WHITE_NITS = 203.0
HDR_HIGHLIGHT_NITS = 1000.0


# --------------------------------------------------------------------------
# the colour maths, forward direction only
# --------------------------------------------------------------------------

_PQ_M1 = 2610.0 / 16384.0
_PQ_M2 = 2523.0 / 4096.0 * 128.0
_PQ_C1 = 3424.0 / 4096.0
_PQ_C2 = 2413.0 / 4096.0 * 32.0
_PQ_C3 = 2392.0 / 4096.0 * 32.0

_HLG_A = 0.17883277
_HLG_B = 1.0 - 4.0 * _HLG_A
_HLG_C = 0.5 - _HLG_A * math.log(4.0 * _HLG_A)

_HLG_PEAK = 1000.0
_HLG_GAMMA = 1.2

BT2020_LUMA = (0.2627, 0.6780, 0.0593)


def _pq_signal(np, nits):
    """SMPTE ST 2084 inverse EOTF: absolute nits to a code value."""
    y = np.clip(nits / 10000.0, 0.0, 1.0)
    yp = np.power(y, _PQ_M1)
    return np.power((_PQ_C1 + _PQ_C2 * yp) / (1.0 + _PQ_C3 * yp), _PQ_M2)


def _hlg_signal(np, nits):
    """Absolute display nits to an ARIB STD-B67 code value.

    Two steps, in this order: undo the display's own OOTF to recover the scene
    light HLG actually stores, then apply the OETF. The OOTF is applied to the
    pixel's luminance and scales all three channels, so inverting it means
    solving for that luminance first - `luma(F) = peak * Ys**gamma` falls
    straight out of the definition.
    """
    luma = nits @ np.asarray(BT2020_LUMA, nits.dtype)
    ys = np.power(np.maximum(luma, 0.0) / _HLG_PEAK, 1.0 / _HLG_GAMMA)
    gain = _HLG_PEAK * np.power(np.maximum(ys, 1e-12), _HLG_GAMMA - 1.0)
    scene = np.clip(nits / np.maximum(gain, 1e-12)[..., None], 0.0, 1.0)
    # The two branches meet at scene light 1/12, where both give exactly 0.5.
    # A square root missing its factor of three lands the lower branch on 0.25
    # instead, which is continuous with nothing and darkens every shadow in the
    # clip by two stops - and looks entirely plausible until the PQ version of
    # the same picture is put next to it.
    return np.where(
        scene <= 1.0 / 12.0,
        np.sqrt(3.0 * scene),
        _HLG_A * np.log(np.maximum(12.0 * scene - _HLG_B, 1e-12)) + _HLG_C,
    )


def _to_yuv444p16(np, signal, kr, kb):
    """R'G'B' code values in 0..1 to a limited-range 10-bit frame.

    Written into the 16-bit planar format PyAV can build a frame from, with the
    10-bit codes shifted up six places, which is exactly what FFmpeg's own
    depth conversion does.
    """
    kg = 1.0 - kr - kb
    r, g, b = signal[..., 0], signal[..., 1], signal[..., 2]
    y = kr * r + kg * g + kb * b
    cb = (b - y) / (2.0 * (1.0 - kb))
    cr = (r - y) / (2.0 * (1.0 - kr))
    out = np.empty(signal.shape, np.uint16)
    out[..., 0] = np.clip(np.round(64.0 + 876.0 * y), 0, 1023) * 64
    out[..., 1] = np.clip(np.round(512.0 + 448.0 * cb), 0, 1023) * 64
    out[..., 2] = np.clip(np.round(512.0 + 448.0 * cr), 0, 1023) * 64
    return out


# --------------------------------------------------------------------------
# the pictures
# --------------------------------------------------------------------------


def _pattern(np, width, height, t, depth=8):
    """A frame with unmistakable orientation: a bright bar along the top edge
    and a dimmer one down the left. If it comes back rotated, the test can
    see it in the pixels rather than having to trust metadata."""
    peak = (1 << depth) - 1
    img = np.zeros((height, width, 3), np.float32)
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float32)
    img[..., 0] = 0.25 * peak + 0.20 * peak * np.sin(xx / 30.0 + t)
    img[..., 1] = 0.25 * peak + 0.20 * peak * np.sin(yy / 22.0 - t)
    img[..., 2] = 0.30 * peak
    img[: max(2, height // 10), :, :] = peak          # top edge, bright
    img[:, : max(2, width // 12), :] = peak * 0.55     # left edge, dimmer
    return img


def _hdr_pattern(np, width, height, t):
    """The same picture, in absolute brightness rather than code values.

    Ordinary indoor levels over most of the frame, a band of true diffuse
    white down the left edge, and a specular highlight along the top - which
    is what real high dynamic range footage looks like as a histogram, and is
    the shape that makes the difference between a correct conversion and a
    washed-out one visible in the pixels. Both bars are neutral, so the test
    that reads them is measuring the transfer curve and not the matrix.
    """
    img = np.zeros((height, width, 3), np.float32)
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float32)
    img[..., 0] = 12.0 + 9.0 * np.sin(xx / 30.0 + t)
    img[..., 1] = 12.0 + 9.0 * np.sin(yy / 22.0 - t)
    img[..., 2] = 16.0
    img[: max(2, height // 10), :, :] = HDR_HIGHLIGHT_NITS   # top edge
    img[:, : max(2, width // 12), :] = HDR_WHITE_NITS        # left edge
    return img


# What FFmpeg calls each colour tag. Named here so the fixtures and the
# assertions cannot drift apart over a magic number.
_BT709, _BT2020_PRIM, _BT2020_NCL = 1, 9, 9
_PQ_TRC, _HLG_TRC = 16, 18


def _video_stream(av, container, colour):
    """The output stream, tagged for whichever colour this clip carries."""
    stream = container.add_stream("libx264", rate=FPS)
    stream.width, stream.height = WIDTH, HEIGHT
    if colour is None:
        stream.pix_fmt = "yuv420p"
        stream.options = {"crf": "4", "preset": "veryfast"}
        return stream

    stream.pix_fmt = "yuv420p10le"
    tags = {
        "pq": ("bt2020", "smpte2084", "bt2020nc",
               _BT2020_PRIM, _PQ_TRC, _BT2020_NCL),
        "hlg": ("bt2020", "arib-std-b67", "bt2020nc",
                _BT2020_PRIM, _HLG_TRC, _BT2020_NCL),
        "sdr10": ("bt709", "bt709", "bt709", _BT709, _BT709, _BT709),
    }[colour]
    prim, trc, matrix, prim_code, trc_code, matrix_code = tags
    stream.options = {
        "crf": "4", "preset": "veryfast",
        "x264-params": f"colorprim={prim}:transfer={trc}:colormatrix={matrix}",
    }
    stream.codec_context.color_primaries = prim_code
    stream.codec_context.color_trc = trc_code
    stream.codec_context.colorspace = matrix_code
    return stream


def _frame_for(av, np, colour, t):
    """One frame, built the way this clip's colour says it should be."""
    if colour is None:
        array = np.clip(_pattern(np, WIDTH, HEIGHT, t, 8), 0, 255)
        return av.VideoFrame.from_ndarray(array.astype(np.uint8),
                                          format="rgb24")
    if colour == "sdr10":
        signal = np.clip(_pattern(np, WIDTH, HEIGHT, t, 8) / 255.0, 0.0, 1.0)
        planes = _to_yuv444p16(np, signal, 0.2126, 0.0722)
    else:
        nits = _hdr_pattern(np, WIDTH, HEIGHT, t)
        signal = (_pq_signal(np, nits) if colour == "pq"
                  else _hlg_signal(np, nits))
        planes = _to_yuv444p16(np, np.clip(signal, 0.0, 1.0), 0.2627, 0.0593)
    return av.VideoFrame.from_ndarray(planes, format="yuv444p16le")


def _encode(av, np, path, *, rotation=0, sar=None, colour=None, vfr=False,
            tracks=1, seconds=SECONDS):
    container = av.open(str(path), "w")
    stream = _video_stream(av, container, colour)
    if sar is not None:
        stream.codec_context.sample_aspect_ratio = sar
    if rotation:
        stream.set_display_rotation(rotation)

    audio = []
    for _index in range(tracks):
        a = container.add_stream("aac", rate=48000)
        a.bit_rate = 96_000
        audio.append(a)

    target = "yuv420p" if colour is None else "yuv420p10le"
    count = int(FPS * seconds)
    for index in range(count):
        if vfr:
            # Uneven on purpose: long gaps then a burst, which is what a
            # screen recorder emits when nothing is moving and then something
            # does.
            t = (index / float(FPS)) + (0.018 if index % 3 == 0 else -0.006)
            t = max(0.0, t)
        else:
            t = index / float(FPS)
        frame = _frame_for(av, np, colour, t)
        frame.pts = int(round(t * 90000))
        frame.time_base = Fraction(1, 90000)
        for packet in stream.encode(frame.reformat(format=target)):
            container.mux(packet)

    for a_index, a in enumerate(audio):
        sr, total, step = 48000, int(48000 * seconds), 1024
        freq = 440.0 * (a_index + 1)
        for start in range(0, total, step):
            times = (np.arange(start, min(start + step, total)) / sr)
            wave = (0.2 * np.sin(2 * np.pi * freq * times)).astype(np.float32)
            af = av.AudioFrame.from_ndarray(
                np.ascontiguousarray(np.tile(wave, (2, 1))),
                format="fltp", layout="stereo",
            )
            af.rate = sr
            af.pts = start
            try:
                for packet in a.encode(af):
                    container.mux(packet)
            except Exception:
                pass
        try:
            for packet in a.encode():
                container.mux(packet)
        except Exception:
            pass

    for packet in stream.encode():
        container.mux(packet)
    container.close()


PLAN = {
    "portrait": {"rotation": 90},
    "upside": {"rotation": 180},
    "anamorphic": {"sar": Fraction(4, 3)},
    "hdr": {"colour": "pq"},
    "hlg": {"colour": "hlg"},
    "phone": {"colour": "hlg", "rotation": 90},
    "sdr10": {"colour": "sdr10"},
    "vfr": {"vfr": True},
    "multitrack": {"tracks": 2},
}
"""Exported so a test can tell a stale corpus from a fresh one. A fixture
folder that is checked only for existence certifies whatever happened to be
built last, which is how a corpus quietly stops testing the thing it names."""


def build(out_dir=OUT) -> list:
    import av
    import numpy as np

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    made = []
    for name, kwargs in PLAN.items():
        path = out_dir / f"{name}.mp4"
        _encode(av, np, path, **kwargs)
        made.append(path)
    return made


def main() -> int:
    try:
        import av  # noqa: F401
        import numpy  # noqa: F401
    except Exception:
        print("fixtures need PyAV and numpy: "
              'pip install "pocketsize[video]"', file=sys.stderr)
        return 1
    for path in build():
        print(f"{path.name:>14}  {path.stat().st_size:>8,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
