"""Gather the licence texts of everything an installer bundles.

The BSD, MIT and Apache licences this project's dependencies carry all require
their notice to travel WITH the binary. Ours travelled with the repository,
which is a different thing: somebody who downloads a Pocketsize installer gets
compiled copies of Pillow, numpy, scipy and several codecs, and until now no
statement of what those are or what terms they arrive under.

    python tools/collect_licences.py --out dist/THIRD-PARTY.txt

Reads installed distribution metadata rather than a hand-kept list, because a
hand-kept list is a second copy of the dependency set and would drift the first
time one changed. What is bundled is decided by `packaging/pocketsize.spec`;
what each thing IS comes from its own wheel.

Deliberately loud about gaps. A wheel that ships no licence text gets a line
saying so rather than being silently omitted - the whole value of this file is
that a reader can tell the difference between "permissively licensed" and "we
did not look".
"""

from __future__ import annotations

import argparse
import sys
from importlib.metadata import Distribution, distributions
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# What the installers actually bundle. Names what IS shipped rather than
# reading the whole environment, because the environment a release is built
# in also contains the two GPL-carrying engines that must never reach a
# binary - see NOT_BUNDLED_GPL below. If that decision is ever revisited,
# this list is one of the places that has to change.
BUNDLED = [
    "pillow",
    "numpy",
    "scipy",
    "ssimulacra2",
    "zopflipy",
    "mozjpeg-lossless-optimization",
    "pywebview",
]

# Deliberately absent from the list above, and the reason is the same for
# both: their compiled payload is GPL, so shipping either inside this
# MIT-licensed bundle would put the whole bundle under GPL. Both remain
# available through pip, where the user's own package manager fetches the
# wheel and this project distributes nothing. Kept as a named constant so the
# notices file can say what is missing and why, rather than being silent
# about it - a reader comparing this against `pip list` should not have to
# guess whether an absence was a decision or an oversight.
NOT_BUNDLED_GPL = {
    "av": "PyAV's wheels carry a complete FFmpeg including GPL x264/x265.",
    "imagequant": ("libimagequant is GPL v3-or-later for open-source use "
                   "(the wheel's BSD text covers only the Python binding)."),
}

HEADER = """Pocketsize — third-party notices
================================

Pocketsize itself is MIT licensed. This application bundles the following
third-party components, each under its own licence. The full text of every
licence that could be recovered from the installed distribution follows.

This file is generated by tools/collect_licences.py from the metadata of the
packages actually installed at build time, so it describes this build rather
than an idea of it.

NOT INCLUDED IN THIS APPLICATION, and why. Two components this project can
use are deliberately absent from the installers, because their compiled code
is GPL-licensed and including it would place this MIT-licensed application
under the GPL. Both remain available to anyone who installs Pocketsize with
pip, where they are fetched by the user's own package manager:

{gpl_notes}
See docs/THIRD_PARTY_NOTICES.md for the full reasoning and what it costs.

"""


def _licence_text(dist: Distribution) -> str:
    """The best full licence text this distribution offers, or "" if none.

    Wheels disagree about where this goes: some ship LICENSE at the dist-info
    root, some under a `licenses/` subdirectory (PEP 639), some only declare a
    classifier and ship no text at all.
    """
    try:
        files = dist.files or []
    except Exception:
        return ""
    wanted = []
    for entry in files:
        name = Path(str(entry)).name.upper()
        if not name.startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")):
            continue
        # Skip the RECORD-style metadata rows and anything that is clearly not
        # the text itself.
        if name.endswith((".PY", ".PYC")):
            continue
        wanted.append(entry)
    for entry in sorted(wanted, key=lambda e: len(str(e))):
        try:
            text = entry.read_text()
        except Exception:
            continue
        if text and text.strip():
            return text.strip()
    return ""


def _declared(dist: Distribution) -> str:
    meta = dist.metadata
    stated = meta.get("License-Expression") or meta.get("License") or ""
    if stated and len(stated) <= 80:
        return stated
    classifiers = [c for c in (meta.get_all("Classifier") or [])
                   if c.startswith("License ::")]
    if classifiers:
        return "; ".join(c.split("::")[-1].strip() for c in classifiers)
    return stated[:80] or "not declared"


def build() -> tuple[str, list]:
    found = {}
    for dist in distributions():
        name = (dist.metadata.get("Name") or "").lower()
        if name:
            found.setdefault(name, dist)

    gpl_notes = "".join(f"  * {name} — {why}\n"
                        for name, why in NOT_BUNDLED_GPL.items())
    parts = [HEADER.format(gpl_notes=gpl_notes)]
    missing = []
    for wanted in BUNDLED:
        dist = found.get(wanted.lower())
        if dist is None:
            missing.append(wanted)
            parts.append(
                f"\n{'-' * 72}\n{wanted}\n{'-' * 72}\n"
                "NOT INSTALLED at the time this file was generated, so no "
                "licence text could be collected. If this component is in the "
                "build, this file is incomplete.\n"
            )
            continue
        version = dist.metadata.get("Version") or "?"
        text = _licence_text(dist)
        parts.append(
            f"\n{'-' * 72}\n{wanted} {version}\n"
            f"Licence (declared): {_declared(dist)}\n{'-' * 72}\n"
        )
        if text:
            parts.append(text + "\n")
        else:
            missing.append(wanted)
            parts.append(
                "This distribution ships no licence text in its metadata. "
                "The declared licence is recorded above; the full text is "
                "available from the project's own repository.\n"
            )
    return "".join(parts), missing


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="dist/THIRD-PARTY.txt",
                        help="where to write the collected notices")
    parser.add_argument("--strict", action="store_true",
                        help="exit 1 if any bundled package yielded no text")
    args = parser.parse_args(argv)

    text, missing = build()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {out} ({len(text.splitlines())} lines, "
          f"{len(BUNDLED) - len(missing)}/{len(BUNDLED)} with full text)")
    if missing:
        print("no licence text recovered for: " + ", ".join(missing))
        if args.strict:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
