"""Copy the design system into the desktop app, so there is only one of it.

`web/` holds the token layer and the self-hosted faces. The desktop app used to
carry its own palette, its own radii, its own two transition shorthands and its
own system-font stack - a second visual identity for the same product, and the
half of it that no gate could see.

The desktop app is served by `pocketsize/server.py` out of `pocketsize/webui/`
and has to work from a pip install with no network, so it needs its own copy of
the files on disk. That copy is produced here and committed, exactly like
`web/destinations.js`: no build step at runtime, and CI re-runs this with
`--check` so a stale copy fails the build rather than quietly diverging.

    python tools/sync_webui_assets.py            # refresh the copies
    python tools/sync_webui_assets.py --check    # exit 1 if any are stale

One transformation is applied on the way across. `web/fonts.css` points at
`/fonts/...`, which is right when the stylesheet is served from the site root
and wrong when it is served from `/webui/`. The copy gets relative `fonts/...`
URLs, which resolve correctly against the stylesheet's own location in both
places. The source file is left alone so the deployed site cannot be affected
by a change made for the desktop app.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
WEBUI = ROOT / "pocketsize" / "webui"

BANNER = (
    "/* COPIED from web/{name} by tools/sync_webui_assets.py - DO NOT EDIT.\n"
    " * Edit the file in web/ and re-run the tool; CI fails on a stale copy. */\n"
)

# Text files, banner-stamped so nobody edits the copy by mistake.
#
# `css/media-accent.css` is here rather than being retyped into the desktop
# app's own <style> block for the reason that block is forbidden from naming a
# colour at all: two copies of a value drift, and this one has to mean the same
# thing in both interfaces or a video is purple in one product and not the
# other. It is the only file from `css/` the desktop app needs, because it is
# the only one that names a colour the token layer does not carry.
STYLESHEETS = [
    "heyoz-tokens.css", "fonts.css",
    # The region sheets. Until 2026-08-25 the desktop app carried its own
    # inline <style> block and its own markup, which is how it came to be
    # running the interface from *before* the UX overhaul: 127 elements in the
    # web app against 84 here, and the whole staged sequence
    # (stage-empty/choose/hero/work), `more-choices`, `plan-fields`, `facts`,
    # `measured` and `versions` missing entirely. The palette was synced and
    # the interface was not, so the two products shared a colour scheme and
    # nothing else.
    "css/base.css", "css/layout.css", "css/controls.css",
    "css/queue.css", "css/compare.css", "css/facts.css",
    "css/media-accent.css",
]

# The presentation layer, shared verbatim.
#
# `engine.js` is deliberately absent and is the only module that is: it owns the
# WebAssembly worker pool, and the desktop app compresses in Python instead.
# Every other module was checked for browser-engine calls before this list was
# written - `new Worker`/`postMessage` appear in engine.js and nowhere else,
# and state.js says in its own header that it touches neither the DOM nor the
# pool. `webui/adapter.js` supplies engine.js's contract over the local HTTP
# API, so the shared modules cannot tell which product they are running in.
#
# Imports between these files are all `./sibling.js`, which is why a flat copy
# into `webui/` resolves unchanged.
MODULES = [
    "js/dom.js", "js/format.js", "js/state.js", "js/views.js",
    "js/settings.js", "js/panels.js", "js/queue.js", "js/render.js",
    "js/compare.js", "js/facts.js", "js/save.js", "js/intake.js",
    "js/theme.js", "js/destinations-bridge.js",
    # The adapter: engine.js's contract answered over the local HTTP API. It
    # lives in web/js/ with the modules it substitutes for so that a change to
    # that contract is made in one directory and both implementations are in
    # front of whoever makes it. The web app never loads it.
    "js/engine-local.js",
    # Last, because it imports every other module and reads most naturally
    # after them. Its engine import is rewritten - see `module()`.
    "js/main.js",
    # Generated by tools/gen_destinations.py from pocketsize/destinations.py,
    # and copied rather than re-derived so both interfaces read one table.
    # `state.js` takes `window.DESTINATIONS` from the bridge, and the bridge
    # takes it from here, so the module graph does not resolve without it.
    #
    # The desktop app used to get destinations a second way, over `/api/state`
    # from the same Python module. Both were correct because both descend from
    # destinations.py, but the values arrived by two routes with two shapes -
    # and `app.html` carried an OLD_DESTINATION_NAMES map to translate names
    # the generator had already renamed. One route removes that.
    "destinations.js",
]

# The faces themselves. Binary, copied verbatim.
FONT_DIR = WEB / "fonts"

# The product's icon. Without one linked, the browser asks for /favicon.ico,
# which is not a static route and so answered 403 - one console error on every
# launch, for years, saying nothing useful.
ICONS = ["favicon.svg"]


# `Path.read_text`/`write_text` only learned `newline=` in 3.13 and 3.10, and
# this package supports 3.9. `Path.open` has always taken it. CI found this:
# every job except ubuntu/3.13 failed on a TypeError, which is the version
# matrix earning its keep.
def _read_exact(path) -> str:
    """File contents with no line-ending translation."""
    with path.open("r", encoding="utf-8", newline="") as fh:
        return fh.read()


def _write_exact(path, text: str) -> None:
    """Write with no line-ending translation, so LF stays LF on Windows."""
    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)


def stylesheet(name: str) -> str:
    text = _read_exact(WEB / name)
    if name == "fonts.css":
        # Root-absolute -> relative, so it resolves under /webui/ too.
        text = text.replace("url('/fonts/", "url('fonts/")
    return BANNER.format(name=name) + text


def module(name: str) -> str:
    """A shared UI module, banner-stamped.

    Imports between these files are all `./sibling.js` and the copies land flat
    in one directory, so the graph resolves identically under `/webui/` with no
    path rewriting - which is what made sharing them cheap.

    One line is rewritten. `main.js` imports the engine statically, and a static
    import cannot be chosen at runtime: the specifier is resolved before any of
    the module's own code runs, so no flag, no `globalThis` check and no
    conditional inside main.js can redirect it. The desktop copy therefore
    points at `engine-local.js` instead.

    The alternative was a dynamic `await import()` in main.js, chosen from a
    global. That would have put a branch in the shared file for the benefit of
    one of its two consumers, made the module graph depend on load order, and
    turned every engine call into a promise for the web build too. A single
    substitution here is the smaller change, and it is asserted on by
    test_design_system so it cannot silently stop happening.

    The banner is a JS comment rather than the CSS one, for the same reason it
    exists at all - somebody opening the copy should be told where the original
    lives before they edit the wrong file.
    """
    text = _read_exact(WEB / name)
    if name == "js/main.js":
        before = text
        text = text.replace('} from "./engine.js";', '} from "./engine-local.js";')
        if text == before:                       # pragma: no cover - guard
            raise SystemExit(
                "sync_webui_assets: main.js no longer imports './engine.js' the "
                "way this tool rewrites it. The desktop app would silently load "
                "the browser engine and every compression would fail with no "
                "worker to answer. Fix the substitution rather than removing it."
            )
    return BANNER.format(name=name) + text


def planned() -> list:
    """[(destination, expected bytes)] for everything this tool owns.

    Sources may sit in a subfolder of `web/` but the copies are always flat in
    `webui/`, because the desktop app serves that directory as one place and
    its links are written accordingly.
    """
    out = [(WEBUI / Path(name).name, stylesheet(name).encode("utf-8"))
           for name in STYLESHEETS]
    out += [(WEBUI / Path(name).name, module(name).encode("utf-8"))
            for name in MODULES]
    for face in sorted(FONT_DIR.glob("*.woff2")):
        out.append((WEBUI / "fonts" / face.name, face.read_bytes()))
    for icon in ICONS:
        out.append((WEBUI / icon, (WEB / icon).read_bytes()))
    return out


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any copy is stale or missing")
    args = parser.parse_args(argv)

    stale = []
    for destination, expected in planned():
        current = destination.read_bytes() if destination.is_file() else None
        # Normalise line endings on text so a CRLF checkout is not mistaken for
        # a stale copy - the same trap web/destinations.js fell into.
        if destination.suffix == ".css" and current is not None:
            current = current.replace(b"\r\n", b"\n")
        if current == expected:
            continue
        stale.append(destination)
        if not args.check:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(expected)

    rel = lambda p: p.relative_to(ROOT).as_posix()  # noqa: E731
    if args.check:
        if stale:
            print("FAIL: the desktop app's copy of the design system is out of date:",
                  file=sys.stderr)
            for d in stale:
                print(f"  {rel(d)}", file=sys.stderr)
            print("Run `python tools/sync_webui_assets.py` and commit the result.",
                  file=sys.stderr)
            return 1
        print(f"desktop design system is current ({len(planned())} files)")
        return 0

    if stale:
        for d in stale:
            print(f"wrote {rel(d)}")
    else:
        print(f"already current ({len(planned())} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
